" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" load plugin bundles
"filetype off
"call pathogen#helptags()
"call pathogen#runtime_append_all_bundles()

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

"set history=1000000		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching

" sane tabs
set shiftwidth=4
set tabstop=4
set expandtab

" 2-space indent for C++
autocmd BufRead,BufNewFile   *.hpp,*.cpp,*.h set shiftwidth=2 tabstop=2

" color long lines
" set textwidth=80
" set colorcolumn=+1
match ErrorMsg '\%>80v.\+'

" no annoying temp files
set noswapfile
set nobackup

" paste mote
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode

filetype plugin on

" bash-like autocomplete behaviour for directories
set wildmode=list:longest

" remember position in file
set viminfo='10,\"100,:20,%,n~/.viminfo
function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END
"""

runtime! vundle.vim
runtime! solarized.vim
runtime! trailing-whitespace.vim

" filetype plugins
syntax on
filetype plugin indent on
filetype plugin on

" Powerline
let g:Powerline_symbols = 'fancy'
set laststatus=2
