# Include executable coming with this repo
export PATH="$HOME/.bin:$PATH"

source ~/.zsh/grml.zsh

# Include local configuration which doesn't go into the repo
# (can also be machine-specific)
if [[ -a ~/.zshrc_local ]]
then
  source ~/.zshrc_local
fi

# Add Android SDK to PATH
export PATH="/opt/android-sdk-update-manager/platform-tools/:${PATH}"

export PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
