# Include executable coming with this repo
export PATH="$HOME/.bin:$PATH"

source ~/.zsh/grml.zsh

# Include local configuration which doesn't go into the repo
# (can also be machine-specific)
if [[ -a ~/.zshrc_local ]]
then
  source ~/.zshrc_local
fi

# Add Android SDK to PATH
export PATH="/opt/android-sdk-update-manager/platform-tools/:${PATH}"
# Add Go binaries
export PATH="/usr/lib/go/bin:${PATH}"

export PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
alias tmux='tmux -2'
export PATH=/usr/lib64/openldap:$PATH
export PATH=/usr/sbin/:$PATH

# Add self-compiles dependencies
export LD_LIBRARY_PATH="$HOME/Development/dist/lib64:$HOME/Development/dist/libexec:$LD_LIBRARY_PATH"
export PATH="$HOME/Development/dist/bin:$PATH"
export PKG_CONFIG_PATH="$HOME/Development/dist/lib/pkgconfig:$PKG_CONFIG_PATH"

alias 'emerge'='sudo emerge --color y --autounmask-write y'
alias 'emerge-update'='emerge -uDNav @world --complete-graph=y @system @selected --with-bdeps=y --deep'

# If not set, use /tmp as the XDG_RUNTIME_DIR
if test -z "${XDG_RUNTIME_DIR}"; then
    export XDG_RUNTIME_DIR=/tmp/${UID}-runtime-dir
    if ! test -d "${XDG_RUNTIME_DIR}"; then
        mkdir "${XDG_RUNTIME_DIR}"
        chmod 0700 "${XDG_RUNTIME_DIR}"
    fi
fi

if [[ -a /usr/bin/virtualenvwrapper.sh ]]
then
    source /usr/bin/virtualenvwrapper.sh
fi
